# Shared environment variables for the servers:
dev_server: "{{ lookup('env', 'DEV_SERVER_IP') }}"
prod_server: "{{ lookup('env', 'PROD_SERVER_IP') }}"
bastion_server: "{{ lookup('env', 'BASTION_SERVER') }}"
bastion_user: "{{ lookup('env', 'BASTION_USER') }}"
bastion_key: "{{ lookup('env', 'BASTION_KEY') }}"
dev_prod_user: "{{ lookup('env', 'DEV_PROD_USER') }}"
pg_db_user: "{{ lookup('env', 'PG_DB_USER') }}"
pg_db_password: "{{ lookup('env', 'PG_DB_PASSWORD') }}"
pg_db_name: "{{ lookup('env', 'PG_DB_NAME') }}"
pg_db_cont_name: "{{ lookup('env', 'PG_DB_CONT_NAME') }}"
container_registry_url: "{{ lookup('env', 'CONTAINER_REGISTRY_URL') }}"
converter_db_user: "{{ lookup('env', 'CONVERTER_DB_USER') }}"
converter_db_password: "{{ lookup('env', 'CONVERTER_DB_PASSWORD') }}"
converter_db_name: "{{ lookup('env', 'CONVERTER_DB_NAME') }}"
pgadmin_email: "{{ lookup('env', 'PGADMIN_EMAIL') }}"
pgadmin_password: "{{ lookup('env', 'PGADMIN_PASSWORD') }}"
pgadmin_port: "{{ lookup('env', 'PGADMIN_PORT') }}"

# lookup('env', ...) makes sure that we don't have sensitive data in the repo and it's managed by the CI/CD
