# Shared environment variables for the servers:
dev_server: "{{ lookup('env', 'DEV_SERVER_IP') }}"
prod_server: "{{ lookup('env', 'PROD_SERVER_IP') }}"
bastion_server: "{{ lookup('env', 'BASTION_SERVER') }}"
bastion_user: "{{ lookup('env', 'BASTION_USER') }}"
bastion_key: "{{ lookup('env', 'BASTION_KEY') }}"
dev_prod_user: "{{ lookup('env', 'DEV_PROD_USER') }}"
pg_db_user: "{{ lookup('env', 'PG_DB_USER') }}"
pg_db_password: "{{ lookup('env', 'PG_DB_PASSWORD') }}"
pg_db_name: "{{ lookup('env', 'PG_DB_NAME') }}"
pg_db_cont_name: "{{ lookup('env', 'PG_DB_CONT_NAME') }}"
container_registry_user: "{{ lookup('env', 'CONTAINER_REGISTRY_USER') }}"
container_registry_password: "{{ lookup('env', 'CONTAINER_REGISTRY_PASSWORD') }}"
container_registry_url: "{{ lookup('env', 'CONTAINER_REGISTRY_URL') }}"
mlservice_version: "{{ lookup('env', 'MLSERVICE_VERSION') }}"

# lookup('env', ...) makes sure that we don't have sensitive data in the repo and it's managed by the CI/CD