- name: Provision Server 
  hosts: "{{ target_server | default('development') }}"
  become: true

  tasks:
    - name: Deploy Converter Service
      ansible.builtin.include_tasks:
        file: tasks/deploy_converter_service.yml