---
- name: Provision Servers
  hosts: all
  become: true
  
  tasks:
    - name: Docker
      ansible.builtin.include_tasks:
        file: tasks/deploy_docker.yml

- name: Provision dev server
  hosts: development
  become: true
  
  tasks:
    - name: Nexus
      ansible.builtin.include_tasks:
        file: tasks/deploy_nexus.yml
      # Needs to be executed after the docker play