---
- name: Log into private registry
  community.docker.docker_login:
    registry_url: "{{ container_registry_url }}"
    username: "{{ container_registry_user }}"
    password: "{{ container_registry_password }}"

- name: Pull ML Service image
  community.docker.docker_image_pull:
    name: "{{ container_registry_url }}/mlservice"
    tag: "{{ mlservice_version }}"

- name: Remove previous ML container
  community.docker.docker_container:
    name: ml-service
    state: absent

- name: Create ML Service container
  community.docker.docker_container:
    name: ml-service
    image: "{{ container_registry_url }}/mlservice:{{ mlservice_version }}"
    ports:
      -  5100:5000
    
