---
- name: Create Docker network
  community.docker.docker_network:
    name: sonarnet
    state: present
  register: network_status

- name: Verify Docker network exists
  ansible.builtin.command:
    cmd: docker network inspect sonarnet
  register: inspect_result
  failed_when: inspect_result.rc != 0

- name: Create volume for PostgreSQL data
  community.docker.docker_volume:
    name: pgdata
    state: present

- name: Start PostgreSQL container
  community.docker.docker_container:
    name: db-server
    image: postgres:13.18
    state: started
    restart_policy: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sonardb
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - name: sonarnet
  when: 
    - network_status.changed == True
