---
- name: Create /etc/docker directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Add insecure registry to daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["registry.at04.devops.jala.university"]
      }
    owner: root
    group: root
    mode: '0644'

- name: Restart Docker service to apply changes
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Login to Docker registry
  community.docker.docker_login:
    registry_url: registry.at04.devops.jala.university
    username: "{{ lookup('env', 'CONTAINER_REGISTRY_USER') }}"
    password: "{{ lookup('env', 'CONTAINER_REGISTRY_PASSWORD') }}"
  register: docker_login_result

- name: Docker logout after successful login
  ansible.builtin.shell: |
    docker logout registry.at04.devops.jala.university
  args:
    executable: /bin/bash
  when: docker_login_result is succeeded
  changed_when: false

