---
- name: Pull nexus image
  community.docker.docker_image_pull:
    name: sonatype/nexus3
    tag: '3.74.0'

- name: Create nexus container
  community.docker.docker_container:
    name: nexus
    image: sonatype/nexus3:3.74.0
    ports:
      - 8081:8081
      - 5000:5000
    volumes:
      - nexus-data:/nexus-data
    restart_policy: always
