all:
  children:
    development:
      hosts:
        dev-server-1:
          ansible_host: "{{ dev_server }}"
    production:
      hosts:
        prod-server-1:
          ansible_host: "{{ prod_server }}"
  vars:
    ansible_connection: ssh
    ansible_user: "{{ dev_prod_user }}"
    ansible_ssh_private_key_file: "{{ bastion_key }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ProxyJump={{ bastion_user }}@{{ bastion_server }}"