name: Configs CI/CD

on: 
  push: 
    branches: 
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Private Keys
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "${{ secrets.USER_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.BASTION_KEY }}" > atbastionkey
        chmod 600 ~/.ssh/id_rsa
        chmod 600 atbastionkey
        cat ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i atbastionkey -J at04@devops.jala.university ubuntu@10.27.5.151 pwd
        
