name: Configs CI/CD

on:
  pull_request:
    branches:
      - main
      
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Docker daemon for insecure registry
      run: |
        echo '{"insecure-registries":["registry.at04.devops.jala.university"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker


