name: Configs CI/CD

on: 
  push: 
    branches: 
      - main
      
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install ansible-lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint

    - name: Run ansible-lint
      run: ansible-lint .

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key to known_host
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_BASTION_SERVER }} > ~/.ssh/known_hosts
        
    - name: Setup SSH Keys
      run: |
        echo "${{ secrets.USER_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.BASTION_KEY }}" > atbastionkey
        chmod 600 ~/.ssh/id_rsa
        chmod 600 atbastionkey

    - name: Ping Target Servers
      run: |
        export BASTION_SERVER=${{ secrets.SSH_BASTION_SERVER }}
        export BASTION_USER=${{ vars.BASTION_SERVER_USER }}
        export DEV_SERVER_IP=${{ secrets.DEV_SERVER_IP }}
        export PROD_SERVER_IP=${{ secrets.PROD_SERVER_IP }}
        export DEV_PROD_USER=${{ vars.DEV_PROD_USER }}
        export BASTION_KEY=atbastionkey
        ansible -i host_vars/inventory.yml all -e @group_vars/vars.yml -m ping

    - name: Check playbooks execution
      run: |
        export BASTION_SERVER=${{ secrets.SSH_BASTION_SERVER }}
        export BASTION_USER=${{ vars.BASTION_SERVER_USER }}
        export DEV_SERVER_IP=${{ secrets.DEV_SERVER_IP }}
        export PROD_SERVER_IP=${{ secrets.PROD_SERVER_IP }}
        export DEV_PROD_USER=${{ vars.DEV_PROD_USER }}
        export BASTION_KEY=atbastionkey
        ansible-playbook playbook.yml -i host_vars/inventory.yml -e @group_vars/vars.yml --check
