name: Configs CI/CD

on:
  pull_request:
    branches:
      - main

env:
  BASTION_SERVER: ${{ secrets.SSH_BASTION_SERVER }}
  BASTION_USER: ${{ vars.BASTION_SERVER_USER }}
  DEV_SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
  DEV_PROD_USER: ${{ vars.DEV_PROD_USER }}
  BASTION_KEY: atbastionkey
  PG_DB_CONT_NAME: ${{ vars.PG_DB_CONT_NAME }}
  PG_DB_USER: ${{ vars.PG_DB_USER }}
  PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
  PG_DB_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
  CONVERTER_DB_USER: ${{ vars.CONVERTER_DB_USER}}
  CONVERTER_DB_PASSWORD: ${{ secrets.CONVERTER_DB_PASSWORD}}
  CONVERTER_DB_NAME: ${{ secrets.CONVERTER_DB_NAME}}
  PGADMIN_EMAIL: ${{ vars.PGADMIN_EMAIL}}
  PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD}}
  PGADMIN_PORT: ${{ vars.PGADMIN_PORT}}
  CONTAINER_REGISTRY_URL: ${{ vars.CONTAINER_REGISTRY_URL }}
      
jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install ansible-lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint

    - name: Run ansible-lint
      run: ansible-lint .

  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key to known_host
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_BASTION_SERVER }} > ~/.ssh/known_hosts
        
    - name: Setup SSH Keys
      run: |
        echo "${{ secrets.USER_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.BASTION_KEY }}" > $BASTION_KEY
        chmod 600 ~/.ssh/id_rsa
        chmod 600 $BASTION_KEY
        
    - name: Ping Target Servers
      run: |
        ansible -i host_vars/inventory.yml all -e @group_vars/vars.yml -m ping

    - name: Check playbooks execution
      run: |
        ansible-playbook playbook.yml -i host_vars/inventory.yml -e @group_vars/vars.yml --check
