name: Configs CI/CD Main

on:
  push:
    branches:
      - main

env:
  BASTION_SERVER: ${{ secrets.SSH_BASTION_SERVER }}
  BASTION_USER: ${{ vars.BASTION_SERVER_USER }}
  DEV_SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
  DEV_PROD_USER: ${{ vars.DEV_PROD_USER }}
  BASTION_KEY: atbastionkey
  PG_DB_CONT_NAME: ${{ vars.PG_DB_CONT_NAME }}
  PG_DB_USER: ${{ vars.PG_DB_USER }}
  PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
  PG_DB_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key to known_host
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_BASTION_SERVER }} > ~/.ssh/known_hosts
        
    - name: Setup SSH Keys
      run: |
        echo "${{ secrets.USER_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.BASTION_KEY }}" > atbastionkey
        chmod 600 ~/.ssh/id_rsa
        chmod 600 atbastionkey

    - name: Ping Target Servers
      run: |
        ansible -i host_vars/inventory.yml all -e @group_vars/vars.yml -m ping

    - name: Provision Servers
      run: |
        ansible-playbook playbook.yml -i host_vars/inventory.yml -e @group_vars/vars.yml